language: ruby
rvm:
  - 2.4.1

cache: bundler

script:
  - bundle exec rake db:setup
  - bundle exec rake spec

services:
  - postgresql

before_script:
    - cp config/database.yml.example config/database.yml
    - bundle exec rubocop
    - psql -c 'create database heros_team_app_test;' -U postgres
